name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g. v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win32
            arch: x64
            ext: zip
          # - os: macos-latest
          #   platform: darwin
          #   arch: x64
          #   ext: zip
          # - os: macos-latest
          #   platform: darwin
          #   arch: arm64
          #   ext: zip

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Build Electron app
        run: pnpm run build

      - name: Package artifact (Windows)
        if: matrix.platform == 'win32'
        run: |
          Compress-Archive -Path "dist/electron/Packaged/Game Lib-*" -DestinationPath "Game-Lib-${{ inputs.tag || github.ref_name }}-${{ matrix.platform }}-${{ matrix.arch }}.zip"

      # - name: Package artifact (macOS)
      #   if: matrix.platform == 'darwin'
      #   run: |
      #     cd dist/electron/Packaged
      #     zip -r -9 "../../../Game-Lib-${{ inputs.tag || github.ref_name }}-${{ matrix.platform }}-${{ matrix.arch }}.zip" "Game Lib.app"

      - name: Create release
        run: |
          gh release view ${{ inputs.tag || github.ref_name }} || gh release create ${{ inputs.tag || github.ref_name }} --generate-notes --title "${{ inputs.tag || github.ref_name }}"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload release asset
        run: |
          gh release upload ${{ inputs.tag || github.ref_name }} "Game-Lib-${{ inputs.tag || github.ref_name }}-${{ matrix.platform }}-${{ matrix.arch }}.zip" --clobber
        env:
          GH_TOKEN: ${{ github.token }}